name: Tests

on: [push]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Install Swiftly
        run: curl -L https://swiftlang.github.io/swiftly/swiftly-install.sh | bash

      - name: Install latest swift version
        run: swiftly install latest

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test
