name: Tests

on: [push]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6"

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test
